### PR TITLE
Sudoko solver code

### PR DESCRIPTION
**Pull request by Bharath-KumarReddy**
Sudoko Solver code in C++ . User has to enter the elements in the Sudoko and while filling 0 is assigned when ever there is blank or empty box then after filling Sudoko , your Sudoko will be solved instantly and you can see the whole Sudoko 9 *9 with all Elements.

Please consider this PR and add a Hacktoberfest_23 label , As I am  very much interested to contribute My self : )

### CODE REVIEW

**Comment by Bharath-KumarReddy** [comment]
This PR contains 

3-D T shirt designer , User can design his own T shirt as per his need .

Sudoko solver code in C++ , user can enter the numbers row by row with 0 if it is blank after filling  9 *9 grid u can see the solution for the sudoko .

Build Sudoko using Html , CSS , JS .

Once please check and merge It , 

Kindly inform incase of further modifications : )

**Comment by Frey0xD** [comment]
Nicely done ✅👍🏼

**Review by ntrunr — APPROVED** [review]

**Comment by Bharath-KumarReddy** [comment]
Can you please change the repo in such a way that it should obey the rules of hacktoberfest_23

As, This PR is excluded due to this repo is not obeying the rules of hacktoberfest

**Comment by Bharath-KumarReddy** [comment]
Hi.
Can you change the repo rules so that it will obey the rules of hacktoberfest_23 , My PR is excluded due to this repo is not obeying the laws or rules of hacktoberfest_23

**Pull request merged**
