### PR TITLE
Docs: Rules and How to Use

### PR DESCRIPTION
**Pull request by RommelTJ**
Resolves https://github.com/LastDeadlock/hacktoberfest/issues/4

Adds Rules and How to Use to `index.html`

### CODE REVIEW

**Comment by LastDeadlock** [comment]
can you also add one img tag including hacktoberfest banner and thank you for the rules

**Comment by RommelTJ** [comment]
@LastDeadlock Happy to do so. I'll make a new PR with a screenshot and you can let me know if it's ok.

**Comment by LastDeadlock** [comment]
Sure that will be great 😃

**Comment by RommelTJ** [comment]
@LastDeadlock Linking on this thread for context https://github.com/LastDeadlock/hacktoberfest/pull/7

**Pull request merged**
